
notifications:
  email: false

git:
  depth: 3
  

matrix:
  include:
    - os: osx
      env: 
        - osv=MacOSX
        - pyv=3.5
      compiler: gcc

    - os: osx
      env: 
        - osv=MacOSX
        - pyv=2.7
      compiler: gcc

    - os: linux
      env: 
        - osv=Linux
        - pyv=3.5
      addons:
        apt:
          packages:
            - gfortran

    - os: linux
      env: 
        - osv=Linux
        - pyv=2.7
      addons:
        apt:
          packages:
            - gfortran


install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-$osv-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes --quiet conda
    - conda create --yes -n test python=$pyv
    - source activate test
    - pip -q install coveralls
    - python setup.py develop

script:
    - coverage run test/test.py -v

after_success:
    - coveralls

